import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AsgardeoProvider } from "@asgardeo/nextjs/server";
import "./globals.css";
import Header from "@/components/Header";
import { connection } from "next/server";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const instant = false;

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Asgardeo depends on request-time values such as the
  // current time, session state, and URL parameters.
  await connection();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense
          fallback={
            <div className="min-h-screen flex items-center justify-center">
              <span className="text-sm text-gray-500">Loading...</span>
            </div>
          }
        >
          <AsgardeoProvider
            afterSignInUrl="/dashboard"
            preferences={{
              theme: {
                inheritFromBranding: false,
              },
            }}
          >
            <Header />
            <main className="flex-1 w-full max-w-xl mx-auto px-6 py-14 flex flex-col gap-7">
              {children}
            </main>
          </AsgardeoProvider>
        </Suspense>
      </body>
    </html>
  );
}
